test:
  adapter: postgresql
  encoding: 'utf8'
  database: orange_test_app_test
  username: lucaspinto
  host: localhost
  port: 5432
development:
  adapter: postgresql
  encoding: 'utf8'
  database: orange_test_app_dev
  username: lucaspinto
  host: localhost
  port: 5432
